modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/chimericdream/enchantment-numbers-fix/issues"
license = "MIT"

[[mods]]
modId = "enchantnumfix"
version = "${version}"
displayName = "Enchantment Numbers Fix"
authors = "chimericdream"
description = '''
Simple mod that converts enchantment levels above 10 to Roman numerals instead of their decimal version.
'''
#logoFile = ""

[[dependencies.enchantnumfix]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchantnumfix]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchantnumfix]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "enchantnumfix.mixins.json"
